import type { AnalyticsPoint, CountingSession } from '@/types/domain';

/**
 * Generate a CSV string from sessions. Suitable for `expo-file-system` writes
 * and `expo-sharing.shareAsync()`.
 */
export function sessionsToCSV(sessions: CountingSession[]): string {
  const header = ['id', 'farmId', 'houseId', 'mode', 'count', 'avgConfidence', 'durationMs', 'createdAt', 'syncStatus'].join(',');
  const rows = sessions.map((s) =>
    [
      s.id,
      s.farmId,
      s.houseId ?? '',
      s.mode,
      s.count,
      s.avgConfidence.toFixed(3),
      s.durationMs,
      new Date(s.createdAt).toISOString(),
      s.syncStatus,
    ].join(','),
  );
  return [header, ...rows].join('\n');
}

/** Build a print-ready HTML doc; pass to `expo-print.printToFileAsync` for PDF. */
export function buildReportHTML(args: {
  farmName: string;
  rangeLabel: string;
  totalBirds: number;
  totalMortality: number;
  series: AnalyticsPoint[];
  sessions: CountingSession[];
}): string {
  const { farmName, rangeLabel, totalBirds, totalMortality, series, sessions } = args;
  const rows = sessions
    .slice(0, 30)
    .map(
      (s) => `
        <tr>
          <td>${new Date(s.createdAt).toLocaleString()}</td>
          <td>${s.mode.toUpperCase()}</td>
          <td>${s.count.toLocaleString()}</td>
          <td>${(s.avgConfidence * 100).toFixed(1)}%</td>
          <td>${(s.durationMs / 1000).toFixed(1)}s</td>
        </tr>`,
    )
    .join('');
  const seriesTable = series
    .slice(-14)
    .map((p) => `<tr><td>${p.date}</td><td>${p.count.toLocaleString()}</td><td>${p.mortality}</td></tr>`)
    .join('');
  return `<!doctype html><html><head><meta charset="utf-8"/><title>Poultra Report</title>
  <style>
    body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#0f1c14;margin:32px;}
    h1{margin:0 0 4px;color:#1f8a3f;}
    h2{margin-top:32px;border-bottom:1px solid #d6e5dc;padding-bottom:4px;}
    .stat-grid{display:flex;gap:16px;margin-top:16px;}
    .stat{flex:1;padding:16px;border-radius:12px;background:#f1faf3;border:1px solid #d6e5dc;}
    .stat .label{font-size:12px;color:#4a6557;text-transform:uppercase;letter-spacing:.05em;}
    .stat .value{font-size:24px;font-weight:700;margin-top:4px;color:#1f8a3f;}
    table{width:100%;border-collapse:collapse;margin-top:12px;font-size:13px;}
    th,td{padding:8px 10px;border-bottom:1px solid #e6efe9;text-align:left;}
    th{background:#f6faf7;color:#3a5547;}
  </style></head>
  <body>
    <h1>Poultra — Farm Report</h1>
    <div style="color:#4a6557">${farmName} · ${rangeLabel}</div>
    <div class="stat-grid">
      <div class="stat"><div class="label">Total birds</div><div class="value">${totalBirds.toLocaleString()}</div></div>
      <div class="stat"><div class="label">Mortality</div><div class="value">${totalMortality}</div></div>
      <div class="stat"><div class="label">Sessions</div><div class="value">${sessions.length}</div></div>
    </div>
    <h2>Recent counting sessions</h2>
    <table><thead><tr><th>When</th><th>Mode</th><th>Count</th><th>Confidence</th><th>Duration</th></tr></thead><tbody>${rows}</tbody></table>
    <h2>14-day trend</h2>
    <table><thead><tr><th>Date</th><th>Birds</th><th>Mortality</th></tr></thead><tbody>${seriesTable}</tbody></table>
    <p style="margin-top:32px;color:#7a8d82;font-size:12px;">Generated by Poultra · ${new Date().toLocaleString()}</p>
  </body></html>`;
}
